gangsters: gangsters.pl
	swipl -q -O -g main --stand_alone=true -o gangsters -c gangsters.pl

towers: towers.pl
	swipl -q -O -g main --stand_alone=true -o towers -c towers.pl

minColoring: minColoring.pl
	swipl -q -O -g main --stand_alone=true -o minColoring -c minColoring.pl

clean:
	rm clauses header model infile.cnf
	rm minColoring gangsters towers
