8:	SAT-alumnes8.cpp
	g++ -O3 -Wall SAT-alumnes8.cpp -o misat

7 :	SAT-alumnes7.cpp
	g++ -O3 -Wall SAT-alumnes7.cpp -o misat

6:	SAT-alumnes6.cpp
	g++ -O3 -Wall SAT-alumnes6.cpp -o misat

5:	SAT-alumnes5.cpp
	g++ -O3 -Wall SAT-alumnes5.cpp -o misat

4:	SAT-alumnes4.cpp
	g++ -O3 -Wall SAT-alumnes4.cpp -o misat

3:	SAT-alumnes3.cpp
	g++ -O3 -Wall SAT-alumnes3.cpp -o misat

2:	SAT-alumnes2.cpp
	g++ -O3 -Wall SAT-alumnes2.cpp -o misat

1:	SAT-alumnes1.cpp
	g++ -O3 -Wall SAT-alumnes1.cpp -o misat

0:	SAT-alumnes0.cpp
	g++ -O3 -Wall SAT-alumnes0.cpp -o misat

t:	template.cpp
	g++ -O3 -Wall template.cpp -o misat




